DB_ALIAS="durango"
DURANGO_HOST="durango.eurofidai.org"
DURANGO_DATABASE="edifact_telekurs"
DURANGO_DRIVERNAME="postgresql"
DURANGO_USERNAME="machinehelene"
DURANGO_PASSWORD="machine@helene.fr"

DB_ALIAS="durango_postgres"
DURANGO_POSTGRES_HOST="durango.eurofidai.org"
DURANGO_POSTGRES_DATABASE="edifact_telekurs"
DURANGO_POSTGRES_DRIVERNAME="postgresql"
DURANGO_POSTGRES_USERNAME="postgres"
DURANGO_POSTGRES_PASSWORD=""

DB_ALIAS="ringo"
RINGO_HOST="ringo.eurofidai.org"
RINGO_DATABASE="eurofidai_telekurs"
RINGO_DRIVERNAME="postgresql"
RINGO_USERNAME="machinelionel"
RINGO_PASSWORD="machine@lionel.fr"

DB_ALIAS="ringo_postgres"
RINGO_POSTGRES_HOST="ringo.eurofidai.org"
RINGO_POSTGRES_DATABASE="eurofidai_telekurs"
RINGO_POSTGRES_DRIVERNAME="postgresql"
RINGO_POSTGRES_USERNAME="postgres"
RINGO_POSTGRES_PASSWORD=""

DB_ALIAS="geronimo_postgres"
GERONIMO_POSTGRES_HOST="geronimo.eurofidai.org"
GERONIMO_POSTGRES_DATABASE="eurofidai_telekurs_v13"
GERONIMO_POSTGRES_DRIVERNAME="postgresql"
GERONIMO_POSTGRES_USERNAME="postgres"
GERONIMO_POSTGRES_PASSWORD=""

DB_ALIAS="yakari"
YAKARI_HOST="yakari.eurofidai.org"
YAKARI_DATABASE="prod_drupal9"
YAKARI_DRIVERNAME="postgresql"
YAKARI_USERNAME="rapport_abonnes"
YAKARI_PASSWORD=""
